name: Deploy new runner machine
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: 3bit/setup-hcloud@v2
      - name: Delete runner if existing
        run: if hcloud server delete runner; then echo; else echo "Error in command to delete server"; fi
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}

      - name: Deploy new runner
        run: |
          curl https://raw.githubusercontent.com/potsdam-pnp/runner/main/.github/workflows/user-data.txt > user-data.txt
          hcloud server create \
            --image ubuntu-22.04 \
            --name runner \
            --type cx11 \
            --ssh-key default-ssh-key \
            --user-data-from-file user-data.txt
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
