name: Deploy new runner machine
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: 3bit/setup-hcloud@v2
      - run: |
          IP=$(ip -6 addr show dev eth0 scope global | grep inet6 | awk -F '[ \t]+|/' '{print $3}')
          curl https://raw.githubusercontent.com/potsdam-pnp/runner/main/.github/workflows/user-data.txt > user-data.txt
          sed -i "s/%IP/$IP/"
          hcloud server create \
            --image ubuntu-22.04 \
            --name runner \
            --type cx11 \
            --without-ipv4 \
            --ssh-key default-ssh-key \
            --user-data-from-file user-data.txt
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
